name: chat-bot-aws-lex

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make install

      - name: Setting up environment variables
        run: |
          echo "IAM_KEY=${{ secrets.IAM_KEY }}" >> .env
          echo "IAM_SECRET=${{ secrets.IAM_SECRET }}" >> .env
          echo "REGION=${{ secrets.REGION }}" >> .env
          echo "BOT_ID=${{ secrets.BOT_ID }}" >> .env
          echo "REGION=${{ secrets.BOT_ALIAS_ID }}" >> .env

      - name: Format the code
        run: |
          make format

      - name: Lint the code
        run: |
          make lint

      - name: Test the code
        run: |
          make test

